version: 2

models:
  - name: stg_bike_trips
    description: Trip happened in nyc from citi bike.
    columns:
      - name: trip_id
        description: >
          Primary key from the specificed bike_id and start_time. 
          The first transaction occurred from the earliest start_time.
        tests:
          - unique
          - not_null
      - name: bike_id
        description: Bike ID to identify an individual bike.
        tests:
          - not_null
      - name: start_time
        description: Timestamp in which a trip begins.
      - name: start_hour
        description: Hours where a trip begins.
        tests:
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
              quote: false
      - name: start_day_of_week
        description: Day of week where a trip begins started with 1 which is sunday.
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7]
              quote: false
      - name: end_time
        description: Timestamp in which a trip ends.
      - name: start_station_id
        description: Location ID where a trip begins.
      - name: end_station_id
        description: Location ID where a trip ends.
      - name: start_station_name
        description: Location name tied with location ID where a trip begins.
      - name: end_station_name
        description: Location name tied with location ID where a trip ends.
      - name: start_station_latitude
        description: Location latitude tied with location ID where a trip begins.
      - name: start_station_longitude
        description: Location longitude tied with location ID where a trip begins.
      - name: end_station_latitude
        description: Location latitude tied with location ID where a trip ends.
      - name: end_station_longitude
        description: Location longitude tied with location ID where a trip ends.
      - name: is_the_same_start_end_station
        description: >
          Flag to check whether a completed trip begins and ends at the same station. 
          1 stands for the same and vice versa.
      - name: trip_duration
        description: Amount of time trip took place in seconds.
      - name: user_type
        description: >
          Type of users who use a service. 
          Customer=24-hour pass or 3-day pass user; Subscriber=Annual member
        tests:
          - accepted_values:
              values: ["Customer", "Subscriber"]
              severity: warn
      - name: gender
        description: Gender of users. 0=unknown; 1=male; 2=female
        tests:
          - accepted_values:
              values: [0, 1, 2]
              quote: false
              severity: warn
      - name: birth_year
        description: Year of birth of users.