version: 2

models:
  - name: partitioned_clustered_bike_trips
    columns:
      - name: start_station_id
        tests:
          - not_null
      - name: end_station_id
        tests:
          - not_null
      - name: usertype
        tests:
          - accepted_values:
              values: ["Customer", "Subscriber"]
      - name: gender
        tests:
          - accepted_values:
              values: [0, 1, 2]
              quote: false
